### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by asmlgkj** [l-magnificence/Mime#11]
Thanks a lot.

**Comment by l-magnificence** [comment]
It run successfully.
Ignore it. When Mime encounter an error in this method, it have retried.

**Comment by asmlgkj** [comment]
[xx.pdf](https://github.com/user-attachments/files/16061343/xx.pdf)
different from the exampld fig

**Comment by asmlgkj** [comment]
Thanks a lot. with the same code as yours, it produce a different figure, especially Enet[a=0.5] your is 0.8.
on the other hand, my figure seems too wide, not as nice as yours, can you show me your save para?
[xx.pdf](https://github.com/user-attachments/files/16065007/xx.pdf)

**Comment by l-magnificence** [comment]
The reason your results change is because of the randomization used to cross-validate the estimates. Due to that same seeds produces different values on different computers, methods such as Enet fit the models to a different training set and cross-validation tests it on a different testing set. 
You can set width and height  to control the size of figure
```
png("./fig/cindex.png",units ="in",width = 6,height = 15,res = 300)
cindex_dis_all()
dev.off()
```
