### ISSUE TITLE
some bug regarding cal_AUC_ml_res and cindex_dis_all

### ISSUE THREAD

**Issue by ksjsy1996926** [l-magnificence/Mime#39]
Hi, thank you very much for the excellent package you provided, however I found some bugs during the run of the program：
1. In forecasting the AUC levels of various models, the values presented in the fourth column of the chart denoted as "mean AUC in validate cohort" seems to pertain to the training cohort. 
![auc_dis_all](https://github.com/user-attachments/assets/0b420139-2da7-49a7-a573-1666a4153f48)
2. Upon scrutinizing each model independently, it is observed that certain models may exhibit AUC and C-index values that surpass 1.
![auc_dis_指定多时间](https://github.com/user-attachments/assets/029a024a-a27e-4c96-b3f5-a2c2c48194cc)

**Comment by l-magnificence** [comment]
1. In auc_dis_all, are you defined right name of validate_set?
2. I don't know what exactly happen when auc >1 as this also happened in DepMap database (https://forum.depmap.org/t/prism-drug-auc-larger-than-1-meaning/241). I think you can covert all >1 auc values to 1 indicating its highest predictive power.

**Comment by ksjsy1996926** [comment]
got it,thank you very much

**Comment by Bingqing-Yang** [comment]
I also have the issue of AUROC over than 1. However the plot of AUROC  looks less than 1. So it is so weird. Theoretically, AUROC should less than 1. You can not just saying convert those model with AUROC over than 1 to 1. I think it must be some ignored in your code. Actually I have revise your code, however do not get the ideal result. If its is possible, could you please double check your code for user-friendly. Because it seems the common issue. Thank you very much for your time and great job.
